"use client";

import { useState, useEffect } from "react";
import { CheckCircle2, XCircle, Search, RefreshCw, Eye } from "lucide-react";
import { format } from "date-fns";
import toast from "react-hot-toast";

export default function ApprovalsPage() {
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchItems();
  }, []);

  const fetchItems = async () => {
    setLoading(true);
    // Simulating a fetch of "Pending QC" items from the AI Agent pipeline
    // In actual implementation this connects to the /api/approvals or /api/library endpoint
    // fetching items with status = 'draft' or 'review'.
    setTimeout(() => {
        setItems([
            { id: 1, type: "LinkedIn Post", preview: "Why NRI's are moving back to Nagpur in 2026...", agent: "Content Writer", status: "Needs Review", date: new Date() },
            { id: 2, type: "Instagram Carousel", preview: "5 hidden costs of buying agricultural land...", agent: "Visual Designer", status: "Needs Review", date: new Date() },
            { id: 3, type: "WhatsApp Sequence", preview: "Hello {Name}, noticed you attended our open house...", agent: "Copywriter", status: "Needs Review", date: new Date() },
        ]);
        setLoading(false);
    }, 1000);
  };

  const handleApprove = (id: number) => {
    // Calls API to change status to "Approved" and schedules it via Distribution Agent
    setItems((prev) => prev.filter(i => i.id !== id));
    toast.success("Approved! The Distribution Agent will now schedule this.");
  };

  const handleReject = (id: number) => {
    // Calls API to toss it back to Content Writer / QC Auditor
    setItems((prev) => prev.filter(i => i.id !== id));
    toast.error("Sent back to the AI Team for revision.");
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6 pb-20 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <h1 className="text-4xl font-black text-gray-900 tracking-tight">Approvals & QC</h1>
          </div>
          <p className="text-gray-500 font-medium">Review content generated by your AI Team before publishing.</p>
        </div>
        <button onClick={fetchItems} className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 text-gray-700 font-bold rounded-xl shadow-sm hover:bg-gray-50 transition-all">
          <RefreshCw className="w-4 h-4" />
          Refresh Pipeline
        </button>
      </div>

      <div className="bg-white border border-gray-100 shadow-sm rounded-3xl overflow-hidden mt-8">
        {loading ? (
            <div className="p-12 text-center text-gray-400 font-medium animate-pulse">
                Fetching pipeline from the Agents...
            </div>
        ) : items.length === 0 ? (
            <div className="p-12 text-center">
                <div className="w-16 h-16 bg-green-50 text-green-500 rounded-2xl flex items-center justify-center mx-auto mb-4">
                    <CheckCircle2 className="w-8 h-8" />
                </div>
                <h3 className="text-xl font-black text-gray-900 mb-2">You're all caught up!</h3>
                <p className="text-gray-500">The AI team doesn't have any pending approvals for you right now.</p>
            </div>
        ) : (
            <div className="divide-y divide-gray-100">
                {items.map((item) => (
                    <div key={item.id} className="p-6 hover:bg-gray-50 transition-colors flex flex-col md:flex-row gap-6 md:items-center justify-between">
                        <div className="flex-1 space-y-2">
                            <div className="flex items-center gap-3">
                                <span className="bg-indigo-50 text-indigo-700 text-[10px] font-black uppercase px-2 py-1 rounded-full border border-indigo-100">
                                    {item.type}
                                </span>
                                <span className="text-xs font-bold text-gray-400 uppercase">From: {item.agent}</span>
                                <span className="text-xs text-gray-400">{format(item.date, "PPp")}</span>
                            </div>
                            <p className="text-gray-900 font-medium pr-8">{item.preview}</p>
                        </div>
                        <div className="flex items-center gap-3 shrink-0">
                            <button className="p-2 text-indigo-600 bg-indigo-50 hover:bg-indigo-100 rounded-xl transition-colors tooltip-target" title="Preview Full">
                                <Eye className="w-5 h-5" />
                            </button>
                            <button onClick={() => handleApprove(item.id)} className="flex items-center gap-2 px-4 py-2 bg-emerald-500 hover:bg-emerald-600 text-white font-bold rounded-xl transition-colors shadow-sm">
                                <CheckCircle2 className="w-5 h-5" />
                                Approve
                            </button>
                            <button onClick={() => handleReject(item.id)} className="flex items-center gap-2 px-4 py-2 bg-red-50 hover:bg-red-100 text-red-600 font-bold rounded-xl transition-colors">
                                <XCircle className="w-5 h-5" />
                                Reject
                            </button>
                        </div>
                    </div>
                ))}
            </div>
        )}
      </div>
    </div>
  );
}
