import { NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";

export const runtime = "nodejs";

/**
 * GET /api/studio/proactive
 * Returns the proactive campaign suggestion generated by the last Gravity Claw run
 * + the campaign performance log stored in contentBrain.contentDna
 */
export async function GET() {
  try {
    const brain = await prisma.contentBrain.findFirst({
      orderBy: { updatedAt: "desc" },
      select: { contentDna: true },
    });

    const dna = (brain?.contentDna as any) || {};

    return NextResponse.json({
      proactiveSuggestion: dna.lastProactiveSuggestion || null,
      campaignLog: (dna.campaignLog || []).slice(-5),     // last 5 campaigns
      lastCampaignAt: dna.lastCampaignAt || null,
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
