import { decryptToken } from "@/lib/utils/encryption";

export interface YouTubePublishRequest {
  accessToken: string;
  title: string;
  description: string;
  privacyStatus?: "public" | "private" | "unlisted";
  videoUrl?: string; 
  tags?: string[];
}

/**
 * YouTube Shorts/Video Publishing.
 * Uses the Resumable Upload flow for stability.
 */
export async function publishToYouTube({
  accessToken,
  title,
  description,
  privacyStatus = "public",
  videoUrl,
  tags = ["RealEstate", "NagpurPlots", "ContentSathi"]
}: YouTubePublishRequest) {
  try {
    const decryptedToken = decryptToken(accessToken);

    // 1. Initialize Resumable Upload
    const metadata = {
      snippet: {
        title: title || "New ContentSathi Short",
        description: description || "Generated by ContentSathi AI",
        tags,
        categoryId: "22", // People & Blogs
      },
      status: {
        privacyStatus,
        selfDeclaredMadeForKids: false,
      },
    };

    const initResponse = await fetch(
      "https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${decryptedToken}`,
          "Content-Type": "application/json; charset=UTF-8",
          "X-Upload-Content-Type": "video/*",
        },
        body: JSON.stringify(metadata),
      }
    );

    if (!initResponse.ok) {
      const errData = await initResponse.json();
      throw new Error(errData.error?.message || "YouTube initialization failed");
    }

    const uploadUrl = initResponse.headers.get("Location");

    if (!uploadUrl) {
      throw new Error("No upload URL returned from YouTube");
    }

    // 2. If videoUrl is provided, we attempt to stream it directly from the source to YouTube
    if (videoUrl) {
      const videoFetch = await fetch(videoUrl);
      if (!videoFetch.ok) throw new Error("Failed to fetch source video from URL");
      
      const videoBlob = await videoFetch.blob();

      const uploadResponse = await fetch(uploadUrl, {
        method: "PUT",
        headers: {
          "Content-Type": "video/*",
          "Content-Length": videoBlob.size.toString(),
        },
        body: videoBlob,
      });

      if (uploadResponse.ok) {
        const finalData = await uploadResponse.json();
        return {
          success: true,
          postId: finalData.id,
          url: `https://youtube.com/shorts/${finalData.id}`,
          message: "YouTube Short published successfully via streaming upload."
        };
      }
    }

    // If no videoUrl or upload interrupted, return the resumable URL for retry/client-side handling
    return {
      success: true,
      uploadUrl,
      postId: "pending_upload",
      message: "YouTube upload initialized. Resumable URL generated.",
      instruction: "Stream video binary to the provided uploadUrl via PUT."
    };

  } catch (error: any) {
    console.error("[YOUTUBE_PUBLISH_ERROR]", error);
    return { success: false, error: error.message };
  }
}
